#
# Copyright (C) 2017 TripNDroid Mobile Engineering
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/bin/ifaadaemon:system/bin/ifaadaemon \
    $(LOCAL_PATH)/proprietary/bin/ipacm-diag:system/bin/ipacm-diag \
    $(LOCAL_PATH)/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    $(LOCAL_PATH)/proprietary/etc/GyroOffset_db.config:system/etc/GyroOffset_db.config \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_workspaceFile.qwsp:system/etc/acdbdata/MTP/MTP_workspaceFile.qwsp \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/adsp_avs_config.acdb:system/etc/acdbdata/adsp_avs_config.acdb \
    $(LOCAL_PATH)/proprietary/etc/camera/camera_config.xml:system/etc/camera/camera_config.xml \
    $(LOCAL_PATH)/proprietary/etc/camera/cp/CPCalibrationData.bin:system/etc/camera/cp/CPCalibrationData.bin \
    $(LOCAL_PATH)/proprietary/etc/camera/cp/FusionCalibrationParams.bin:system/etc/camera/cp/FusionCalibrationParams.bin \
    $(LOCAL_PATH)/proprietary/etc/camera/cp/SystemParamsBokeh.bin:system/etc/camera/cp/SystemParamsBokeh.bin \
    $(LOCAL_PATH)/proprietary/etc/camera/cp/SystemParamsFusion.bin:system/etc/camera/cp/SystemParamsFusion.bin \
    $(LOCAL_PATH)/proprietary/etc/camera/imx350_chromatix.xml:system/etc/camera/imx350_chromatix.xml \
    $(LOCAL_PATH)/proprietary/etc/camera/imx371_chromatix.xml:system/etc/camera/imx371_chromatix.xml \
    $(LOCAL_PATH)/proprietary/etc/camera/imx398_chromatix.xml:system/etc/camera/imx398_chromatix.xml \
    $(LOCAL_PATH)/proprietary/etc/firmware/a530_pfp.fw:system/etc/firmware/a530_pfp.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a530_pm4.fw:system/etc/firmware/a530_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a540_gpmu.fw2:system/etc/firmware/a540_gpmu.fw2 \
    $(LOCAL_PATH)/proprietary/etc/firmware/a540_zap.b00:system/etc/firmware/a540_zap.b00 \
    $(LOCAL_PATH)/proprietary/etc/firmware/a540_zap.b01:system/etc/firmware/a540_zap.b01 \
    $(LOCAL_PATH)/proprietary/etc/firmware/a540_zap.b02:system/etc/firmware/a540_zap.b02 \
    $(LOCAL_PATH)/proprietary/etc/firmware/a540_zap.elf:system/etc/firmware/a540_zap.elf \
    $(LOCAL_PATH)/proprietary/etc/firmware/a540_zap.mdt:system/etc/firmware/a540_zap.mdt \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_10_0.fw:system/etc/firmware/cpp_firmware_v1_10_0.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_12_0.fw:system/etc/firmware/cpp_firmware_v1_12_0.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_5_0.fw:system/etc/firmware/cpp_firmware_v1_5_0.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_5_2.fw:system/etc/firmware/cpp_firmware_v1_5_2.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_6_0.fw:system/etc/firmware/cpp_firmware_v1_6_0.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_8_0.fw:system/etc/firmware/cpp_firmware_v1_8_0.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/ipa_fws.b00:system/etc/firmware/ipa_fws.b00 \
    $(LOCAL_PATH)/proprietary/etc/firmware/ipa_fws.b01:system/etc/firmware/ipa_fws.b01 \
    $(LOCAL_PATH)/proprietary/etc/firmware/ipa_fws.b02:system/etc/firmware/ipa_fws.b02 \
    $(LOCAL_PATH)/proprietary/etc/firmware/ipa_fws.b03:system/etc/firmware/ipa_fws.b03 \
    $(LOCAL_PATH)/proprietary/etc/firmware/ipa_fws.b04:system/etc/firmware/ipa_fws.b04 \
    $(LOCAL_PATH)/proprietary/etc/firmware/ipa_fws.mdt:system/etc/firmware/ipa_fws.mdt \
    $(LOCAL_PATH)/proprietary/etc/firmware/mbn_ota/mbn_ota.txt:system/etc/firmware/mbn_ota/mbn_ota.txt \
    $(LOCAL_PATH)/proprietary/etc/firmware/tfa98xx.cnt:system/etc/firmware/tfa98xx.cnt \
    $(LOCAL_PATH)/proprietary/etc/firmware/tp/fw_synaptics_15801.img:system/etc/firmware/tp/fw_synaptics_15801.img \
    $(LOCAL_PATH)/proprietary/etc/firmware/tp/fw_synaptics_15801b.img:system/etc/firmware/tp/fw_synaptics_15801b.img \
    $(LOCAL_PATH)/proprietary/etc/firmware/tp/fw_synaptics_16859.img:system/etc/firmware/tp/fw_synaptics_16859.img \
    $(LOCAL_PATH)/proprietary/etc/fsync_db.config:system/etc/fsync_db.config \
    $(LOCAL_PATH)/proprietary/etc/oneplus5_vstab_db_1080p_video_0_30fps.config:system/etc/oneplus5_vstab_db_1080p_video_0_30fps.config \
    $(LOCAL_PATH)/proprietary/etc/oneplus5_vstab_db_1080p_video_0_60fps.config:system/etc/oneplus5_vstab_db_1080p_video_0_60fps.config \
    $(LOCAL_PATH)/proprietary/etc/oneplus5_vstab_db_1080p_video_1_30fps.config:system/etc/oneplus5_vstab_db_1080p_video_1_30fps.config \
    $(LOCAL_PATH)/proprietary/etc/oneplus5_vstab_db_4k_video_0_30fps.config:system/etc/oneplus5_vstab_db_4k_video_0_30fps.config \
    $(LOCAL_PATH)/proprietary/etc/oneplus5_vstab_db_720p_video_0_30fps.config:system/etc/oneplus5_vstab_db_720p_video_0_30fps.config \
    $(LOCAL_PATH)/proprietary/etc/oneplus5_vstab_db_720p_video_1_30fps.config:system/etc/oneplus5_vstab_db_720p_video_1_30fps.config \
    $(LOCAL_PATH)/proprietary/etc/sensors/sensor_def_qcomdev.conf:system/etc/sensors/sensor_def_qcomdev.conf \
    $(LOCAL_PATH)/proprietary/lib/hw/camera.msm8998.so:system/lib/hw/camera.msm8998.so \
    $(LOCAL_PATH)/proprietary/lib/libFNVfbEngineHAL.so:system/lib/libFNVfbEngineHAL.so \
    $(LOCAL_PATH)/proprietary/lib/libSensorManagerHAL.so:system/lib/libSensorManagerHAL.so \
    $(LOCAL_PATH)/proprietary/lib/libVDBlurlessAPI.so:system/lib/libVDBlurlessAPI.so \
    $(LOCAL_PATH)/proprietary/lib/libVDHDRAPI.so:system/lib/libVDHDRAPI.so \
    $(LOCAL_PATH)/proprietary/lib/lib_oneplus_facebeauty.so:system/lib/lib_oneplus_facebeauty.so \
    $(LOCAL_PATH)/proprietary/lib/lib_oneplus_md.so:system/lib/lib_oneplus_md.so \
    $(LOCAL_PATH)/proprietary/lib/lib_oneplus_watermark.so:system/lib/lib_oneplus_watermark.so \
    $(LOCAL_PATH)/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    $(LOCAL_PATH)/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    $(LOCAL_PATH)/proprietary/lib/libmms_gyro_vstab.so:system/lib/libmms_gyro_vstab.so \
    $(LOCAL_PATH)/proprietary/lib/libmms_gyro_vstab_auth.so:system/lib/libmms_gyro_vstab_auth.so \
    $(LOCAL_PATH)/proprietary/lib/libmms_hal_vstab.so:system/lib/libmms_hal_vstab.so \
    $(LOCAL_PATH)/proprietary/lib/libmms_warper_vstab.so:system/lib/libmms_warper_vstab.so \
    $(LOCAL_PATH)/proprietary/lib/libmorpho_image_stab4.so:system/lib/libmorpho_image_stab4.so \
    $(LOCAL_PATH)/proprietary/lib/libmorpho_video_refiner.so:system/lib/libmorpho_video_refiner.so \
    $(LOCAL_PATH)/proprietary/lib/libopcamera.so:system/lib/libopcamera.so \
    $(LOCAL_PATH)/proprietary/lib/libopcamera_crypt.so:system/lib/libopcamera_crypt.so \
    $(LOCAL_PATH)/proprietary/lib/libopcamera_native_modules.so:system/lib/libopcamera_native_modules.so \
    $(LOCAL_PATH)/proprietary/lib/libopcameralib.so:system/lib/libopcameralib.so \
    $(LOCAL_PATH)/proprietary/lib/libopposfr.so:system/lib/libopposfr.so \
    $(LOCAL_PATH)/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    $(LOCAL_PATH)/proprietary/lib/libteeclientjni.so:system/lib/libteeclientjni.so \
    $(LOCAL_PATH)/proprietary/lib/rfsa/adsp/libVDHexagonBlurless_skel.so:system/lib/rfsa/adsp/libVDHexagonBlurless_skel.so \
    $(LOCAL_PATH)/proprietary/lib/rfsa/adsp/libmorpho_image_stabilizer4_hvx_skel.so:system/lib/rfsa/adsp/libmorpho_image_stabilizer4_hvx_skel.so \
    $(LOCAL_PATH)/proprietary/lib/rfsa/adsp/libmorpho_video_denoiser_hvx_skel.so:system/lib/rfsa/adsp/libmorpho_video_denoiser_hvx_skel.so \
    $(LOCAL_PATH)/proprietary/lib64/hw/fingerprint.msm8998.so:system/lib64/hw/fingerprint.msm8998.so \
    $(LOCAL_PATH)/proprietary/lib64/lib_fpc_tac_shared.so:system/lib64/lib_fpc_tac_shared.so \
    $(LOCAL_PATH)/proprietary/lib64/libparam.so:system/lib64/libparam.so \
    $(LOCAL_PATH)/proprietary/lib64/libteeclientjni.so:system/lib64/libteeclientjni.so \
    $(LOCAL_PATH)/proprietary/lib64/libteeclientjniv2.so:system/lib64/libteeclientjniv2.so \
    $(LOCAL_PATH)/proprietary/vendor/etc/sensors/hals.conf:system/vendor/etc/sensors/hals.conf \
    $(LOCAL_PATH)/proprietary/vendor/firmware/libpn553_fw.so:system/vendor/firmware/libpn553_fw.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libSonyIMX350PdafLibrary.so:system/vendor/lib/libSonyIMX350PdafLibrary.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libSonyIMX371RmscLibrary.so:system/vendor/lib/libSonyIMX371RmscLibrary.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libStDualCam.so:system/vendor/lib/libStDualCam.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libStereoblur.so:system/vendor/lib/libStereoblur.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_lc898217xc_imx350.so:system/vendor/lib/libactuator_lc898217xc_imx350.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_lc898217xc_imx398.so:system/vendor/lib/libactuator_lc898217xc_imx398.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libarcsoft_dualcam_refocus.so:system/vendor/lib/libarcsoft_dualcam_refocus.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libblurbuster.so:system/vendor/lib/libblurbuster.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcamera_bokeh_wrapper.so:system/vendor/lib/libcamera_bokeh_wrapper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcdsprpc.so:system/vendor/lib/libcdsprpc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromaflash.so:system/vendor/lib/libchromaflash.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_3a_1536x866_30fps_video.so:system/vendor/lib/libchromatix_imx350_3a_1536x866_30fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_3a_2304x1300_30fps_preview.so:system/vendor/lib/libchromatix_imx350_3a_2304x1300_30fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_3a_2304x1300_30fps_video.so:system/vendor/lib/libchromatix_imx350_3a_2304x1300_30fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_3a_2592x1940_24fps_preview_bokeh.so:system/vendor/lib/libchromatix_imx350_3a_2592x1940_24fps_preview_bokeh.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_3a_4160x3120_30fps_preview_bokeh.so:system/vendor/lib/libchromatix_imx350_3a_4160x3120_30fps_preview_bokeh.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_3a_4608x3456_27fps_preview.so:system/vendor/lib/libchromatix_imx350_3a_4608x3456_27fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_3a_5184x3880_30fps_preview.so:system/vendor/lib/libchromatix_imx350_3a_5184x3880_30fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_common.so:system/vendor/lib/libchromatix_imx350_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_cpp_1536x866_30fps_video.so:system/vendor/lib/libchromatix_imx350_cpp_1536x866_30fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_cpp_2304x1300_30fps_video.so:system/vendor/lib/libchromatix_imx350_cpp_2304x1300_30fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_cpp_4160x3120_30fps_preview_bokeh.so:system/vendor/lib/libchromatix_imx350_cpp_4160x3120_30fps_preview_bokeh.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_cpp_4160x3120_30fps_snapshot_bokeh.so:system/vendor/lib/libchromatix_imx350_cpp_4160x3120_30fps_snapshot_bokeh.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_cpp_4608x3456_27fps_preview.so:system/vendor/lib/libchromatix_imx350_cpp_4608x3456_27fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_cpp_4608x3456_27fps_snapshot.so:system/vendor/lib/libchromatix_imx350_cpp_4608x3456_27fps_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_cpp_5184x3880_30fps_preview.so:system/vendor/lib/libchromatix_imx350_cpp_5184x3880_30fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_cpp_5184x3880_30fps_snapshot.so:system/vendor/lib/libchromatix_imx350_cpp_5184x3880_30fps_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_isp_1536x866_30fps_video.so:system/vendor/lib/libchromatix_imx350_isp_1536x866_30fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_isp_2304x1300_30fps_video.so:system/vendor/lib/libchromatix_imx350_isp_2304x1300_30fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_isp_4160x3120_30fps_snapshot_bokeh.so:system/vendor/lib/libchromatix_imx350_isp_4160x3120_30fps_snapshot_bokeh.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_isp_4608x3456_27fps_snapshot.so:system/vendor/lib/libchromatix_imx350_isp_4608x3456_27fps_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_isp_5184x3880_30fps_snapshot.so:system/vendor/lib/libchromatix_imx350_isp_5184x3880_30fps_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx350_postproc.so:system/vendor/lib/libchromatix_imx350_postproc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_3a_2304x1728_30fps_auto_hdr.so:system/vendor/lib/libchromatix_imx371_3a_2304x1728_30fps_auto_hdr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_3a_2304x1728_30fps_hdr.so:system/vendor/lib/libchromatix_imx371_3a_2304x1728_30fps_hdr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_3a_2304x1728_30fps_preview.so:system/vendor/lib/libchromatix_imx371_3a_2304x1728_30fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_3a_2304x1728_30fps_video.so:system/vendor/lib/libchromatix_imx371_3a_2304x1728_30fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_3a_4656x3456_30fps_preview.so:system/vendor/lib/libchromatix_imx371_3a_4656x3456_30fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_common.so:system/vendor/lib/libchromatix_imx371_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_cpp_2304x1728_30fps_flash.so:system/vendor/lib/libchromatix_imx371_cpp_2304x1728_30fps_flash.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_cpp_2304x1728_30fps_hdr.so:system/vendor/lib/libchromatix_imx371_cpp_2304x1728_30fps_hdr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_cpp_2304x1728_30fps_liveshot.so:system/vendor/lib/libchromatix_imx371_cpp_2304x1728_30fps_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_cpp_2304x1728_30fps_preview.so:system/vendor/lib/libchromatix_imx371_cpp_2304x1728_30fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_cpp_2304x1728_30fps_snapshot.so:system/vendor/lib/libchromatix_imx371_cpp_2304x1728_30fps_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_cpp_2304x1728_30fps_video.so:system/vendor/lib/libchromatix_imx371_cpp_2304x1728_30fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_cpp_4656x3456_30fps_snapshot.so:system/vendor/lib/libchromatix_imx371_cpp_4656x3456_30fps_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_isp_2304x1728_30fps_snapshot.so:system/vendor/lib/libchromatix_imx371_isp_2304x1728_30fps_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_isp_2304x1728_30fps_video.so:system/vendor/lib/libchromatix_imx371_isp_2304x1728_30fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_isp_4656x3456_30fps_snapshot.so:system/vendor/lib/libchromatix_imx371_isp_4656x3456_30fps_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx371_postproc.so:system/vendor/lib/libchromatix_imx371_postproc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_3a_1476x834_120fps_video.so:system/vendor/lib/libchromatix_imx398_3a_1476x834_120fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_3a_2328x1304_60fps_video.so:system/vendor/lib/libchromatix_imx398_3a_2328x1304_60fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_3a_3264x2448_24fps_preview_bokeh.so:system/vendor/lib/libchromatix_imx398_3a_3264x2448_24fps_preview_bokeh.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_3a_3264x2448_30fps_preview_bokeh.so:system/vendor/lib/libchromatix_imx398_3a_3264x2448_30fps_preview_bokeh.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_3a_4656x2608_30fps_preview.so:system/vendor/lib/libchromatix_imx398_3a_4656x2608_30fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_3a_4656x2608_30fps_video.so:system/vendor/lib/libchromatix_imx398_3a_4656x2608_30fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_3a_4656x2608_30fps_video_4k.so:system/vendor/lib/libchromatix_imx398_3a_4656x2608_30fps_video_4k.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_3a_4656x3496_30fps_preview.so:system/vendor/lib/libchromatix_imx398_3a_4656x3496_30fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_3a_hq.so:system/vendor/lib/libchromatix_imx398_3a_hq.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_3a_manual.so:system/vendor/lib/libchromatix_imx398_3a_manual.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_3a_panorama.so:system/vendor/lib/libchromatix_imx398_3a_panorama.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_3a_wechat_preview.so:system/vendor/lib/libchromatix_imx398_3a_wechat_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_common.so:system/vendor/lib/libchromatix_imx398_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_1476x834_120fps_video.so:system/vendor/lib/libchromatix_imx398_cpp_1476x834_120fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_2328x1304_60fps_video.so:system/vendor/lib/libchromatix_imx398_cpp_2328x1304_60fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_3264x2448_30fps_preview_bokeh.so:system/vendor/lib/libchromatix_imx398_cpp_3264x2448_30fps_preview_bokeh.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_3264x2448_30fps_snapshot_bokeh.so:system/vendor/lib/libchromatix_imx398_cpp_3264x2448_30fps_snapshot_bokeh.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_4656x2608_30fps_preview.so:system/vendor/lib/libchromatix_imx398_cpp_4656x2608_30fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_4656x2608_30fps_video.so:system/vendor/lib/libchromatix_imx398_cpp_4656x2608_30fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_4656x2608_30fps_video_4k.so:system/vendor/lib/libchromatix_imx398_cpp_4656x2608_30fps_video_4k.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_4656x3496_30fps_preview.so:system/vendor/lib/libchromatix_imx398_cpp_4656x3496_30fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_4656x3496_30fps_snapshot.so:system/vendor/lib/libchromatix_imx398_cpp_4656x3496_30fps_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_snapshot_flash.so:system/vendor/lib/libchromatix_imx398_cpp_snapshot_flash.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_snapshot_hdr.so:system/vendor/lib/libchromatix_imx398_cpp_snapshot_hdr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_snapshot_manual.so:system/vendor/lib/libchromatix_imx398_cpp_snapshot_manual.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_cpp_snapshot_nomultiframe.so:system/vendor/lib/libchromatix_imx398_cpp_snapshot_nomultiframe.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_isp_1476x834_120fps_video.so:system/vendor/lib/libchromatix_imx398_isp_1476x834_120fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_isp_2328x1304_60fps_video.so:system/vendor/lib/libchromatix_imx398_isp_2328x1304_60fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_isp_3264x2448_30fps_snapshot_bokeh.so:system/vendor/lib/libchromatix_imx398_isp_3264x2448_30fps_snapshot_bokeh.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_isp_4656x2608_30fps_video.so:system/vendor/lib/libchromatix_imx398_isp_4656x2608_30fps_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_isp_4656x3496_30fps_preview.so:system/vendor/lib/libchromatix_imx398_isp_4656x3496_30fps_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_isp_4656x3496_30fps_snapshot.so:system/vendor/lib/libchromatix_imx398_isp_4656x3496_30fps_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_isp_manual.so:system/vendor/lib/libchromatix_imx398_isp_manual.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_isp_panorama.so:system/vendor/lib/libchromatix_imx398_isp_panorama.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_isp_zsl_snapshot.so:system/vendor/lib/libchromatix_imx398_isp_zsl_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_postproc.so:system/vendor/lib/libchromatix_imx398_postproc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx398_preview_1080p_cpp.so:system/vendor/lib/libchromatix_imx398_preview_1080p_cpp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcvface_api.so:system/vendor/lib/libcvface_api.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdczoom.so:system/vendor/lib/libdczoom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdualcameraddm.so:system/vendor/lib/libdualcameraddm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libfiltergenerator.so:system/vendor/lib/libfiltergenerator.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libflash_pmic.so:system/vendor/lib/libflash_pmic.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libfusionLibrary.so:system/vendor/lib/libfusionLibrary.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjni_blurbuster.so:system/vendor/lib/libjni_blurbuster.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjni_chromaflash.so:system/vendor/lib/libjni_chromaflash.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjni_dualcamera.so:system/vendor/lib/libjni_dualcamera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjni_filtergenerator.so:system/vendor/lib/libjni_filtergenerator.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjni_makeupV2.so:system/vendor/lib/libjni_makeupV2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjni_optizoom.so:system/vendor/lib/libjni_optizoom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjni_panorama.so:system/vendor/lib/libjni_panorama.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjni_sharpshooter.so:system/vendor/lib/libjni_sharpshooter.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjni_stillmore.so:system/vendor/lib/libjni_stillmore.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjni_trackingfocus.so:system/vendor/lib/libjni_trackingfocus.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjni_ubifocus.so:system/vendor/lib/libjni_ubifocus.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjpegdmahw.so:system/vendor/lib/libjpegdmahw.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_mct.so:system/vendor/lib/libmmcamera2_mct.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_mct_shimlayer.so:system/vendor/lib/libmmcamera2_mct_shimlayer.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_pp_buf_mgr.so:system/vendor/lib/libmmcamera2_pp_buf_mgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_stats_lib.so:system/vendor/lib/libmmcamera2_stats_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_chromaflash_lib.so:system/vendor/lib/libmmcamera_chromaflash_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_dbg.so:system/vendor/lib/libmmcamera_dbg.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_dummyalgo.so:system/vendor/lib/libmmcamera_dummyalgo.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_edgesmooth_lib.so:system/vendor/lib/libmmcamera_edgesmooth_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_eebinparse.so:system/vendor/lib/libmmcamera_eebinparse.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_eeprom_util.so:system/vendor/lib/libmmcamera_eeprom_util.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_eztune_module.so:system/vendor/lib/libmmcamera_eztune_module.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_facedetection_lib.so:system/vendor/lib/libmmcamera_facedetection_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_faceproc2.so:system/vendor/lib/libmmcamera_faceproc2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_hvx_add_constant.so:system/vendor/lib/libmmcamera_hvx_add_constant.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_hvx_grid_sum.so:system/vendor/lib/libmmcamera_hvx_grid_sum.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_imglib_faceproc_adspstub.so:system/vendor/lib/libmmcamera_imglib_faceproc_adspstub.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_imglib_faceproc_adspstub2.so:system/vendor/lib/libmmcamera_imglib_faceproc_adspstub2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_imx350.so:system/vendor/lib/libmmcamera_imx350.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_imx350_gt24c64ass_eeprom.so:system/vendor/lib/libmmcamera_imx350_gt24c64ass_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_imx371.so:system/vendor/lib/libmmcamera_imx371.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_imx398.so:system/vendor/lib/libmmcamera_imx398.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_imx398_gt24c64_eeprom.so:system/vendor/lib/libmmcamera_imx398_gt24c64_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_abf48.so:system/vendor/lib/libmmcamera_isp_abf48.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_aec_bg_stats47.so:system/vendor/lib/libmmcamera_isp_aec_bg_stats47.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_bf_stats47.so:system/vendor/lib/libmmcamera_isp_bf_stats47.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_bg_stats46.so:system/vendor/lib/libmmcamera_isp_bg_stats46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_bhist_stats44.so:system/vendor/lib/libmmcamera_isp_bhist_stats44.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_black_level48.so:system/vendor/lib/libmmcamera_isp_black_level48.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_bpc48.so:system/vendor/lib/libmmcamera_isp_bpc48.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_cac47.so:system/vendor/lib/libmmcamera_isp_cac47.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_chroma_enhan40.so:system/vendor/lib/libmmcamera_isp_chroma_enhan40.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_chroma_suppress40.so:system/vendor/lib/libmmcamera_isp_chroma_suppress40.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_clamp_encoder40.so:system/vendor/lib/libmmcamera_isp_clamp_encoder40.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_clamp_video40.so:system/vendor/lib/libmmcamera_isp_clamp_video40.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:system/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_color_correct46.so:system/vendor/lib/libmmcamera_isp_color_correct46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_color_xform_encoder46.so:system/vendor/lib/libmmcamera_isp_color_xform_encoder46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_color_xform_video46.so:system/vendor/lib/libmmcamera_isp_color_xform_video46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_color_xform_viewfinder46.so:system/vendor/lib/libmmcamera_isp_color_xform_viewfinder46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_cs_stats46.so:system/vendor/lib/libmmcamera_isp_cs_stats46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_demosaic48.so:system/vendor/lib/libmmcamera_isp_demosaic48.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_demux48.so:system/vendor/lib/libmmcamera_isp_demux48.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_fovcrop_encoder46.so:system/vendor/lib/libmmcamera_isp_fovcrop_encoder46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_fovcrop_video46.so:system/vendor/lib/libmmcamera_isp_fovcrop_video46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_fovcrop_viewfinder46.so:system/vendor/lib/libmmcamera_isp_fovcrop_viewfinder46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_gamma44.so:system/vendor/lib/libmmcamera_isp_gamma44.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_gic48.so:system/vendor/lib/libmmcamera_isp_gic48.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_gtm46.so:system/vendor/lib/libmmcamera_isp_gtm46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_hdr48.so:system/vendor/lib/libmmcamera_isp_hdr48.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_hdr_be_stats46.so:system/vendor/lib/libmmcamera_isp_hdr_be_stats46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_hdr_bhist_stats44.so:system/vendor/lib/libmmcamera_isp_hdr_bhist_stats44.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_ihist_stats46.so:system/vendor/lib/libmmcamera_isp_ihist_stats46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_linearization40.so:system/vendor/lib/libmmcamera_isp_linearization40.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_ltm47.so:system/vendor/lib/libmmcamera_isp_ltm47.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_luma_adaptation40.so:system/vendor/lib/libmmcamera_isp_luma_adaptation40.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_mce40.so:system/vendor/lib/libmmcamera_isp_mce40.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_mesh_rolloff44.so:system/vendor/lib/libmmcamera_isp_mesh_rolloff44.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_pdaf48.so:system/vendor/lib/libmmcamera_isp_pdaf48.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_pedestal_correct46.so:system/vendor/lib/libmmcamera_isp_pedestal_correct46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_rs_stats46.so:system/vendor/lib/libmmcamera_isp_rs_stats46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_scaler_encoder46.so:system/vendor/lib/libmmcamera_isp_scaler_encoder46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_scaler_video46.so:system/vendor/lib/libmmcamera_isp_scaler_video46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_scaler_viewfinder46.so:system/vendor/lib/libmmcamera_isp_scaler_viewfinder46.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_sce40.so:system/vendor/lib/libmmcamera_isp_sce40.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_snr47.so:system/vendor/lib/libmmcamera_isp_snr47.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_isp_sub_module.so:system/vendor/lib/libmmcamera_isp_sub_module.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_llvd.so:system/vendor/lib/libmmcamera_llvd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_optizoom_lib.so:system/vendor/lib/libmmcamera_optizoom_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_paaf_lib.so:system/vendor/lib/libmmcamera_paaf_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ppbase_module.so:system/vendor/lib/libmmcamera_ppbase_module.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ppeiscore.so:system/vendor/lib/libmmcamera_ppeiscore.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_quadracfa.so:system/vendor/lib/libmmcamera_quadracfa.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sac_lib.so:system/vendor/lib/libmmcamera_sac_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sat_dummy_lib.so:system/vendor/lib/libmmcamera_sat_dummy_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sony_imx371_eeprom.so:system/vendor/lib/libmmcamera_sony_imx371_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_stillmore_lib.so:system/vendor/lib/libmmcamera_stillmore_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sw2d_lib.so:system/vendor/lib/libmmcamera_sw2d_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_thread_services.so:system/vendor/lib/libmmcamera_thread_services.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_trueportrait_lib.so:system/vendor/lib/libmmcamera_trueportrait_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_tuning_lookup.so:system/vendor/lib/libmmcamera_tuning_lookup.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ubifocus_lib.so:system/vendor/lib/libmmcamera_ubifocus_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmqjpegdma.so:system/vendor/lib/libmmqjpegdma.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmpbase.so:system/vendor/lib/libmpbase.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liboptizoom.so:system/vendor/lib/liboptizoom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqomx_jpegenc_pipe.so:system/vendor/lib/libqomx_jpegenc_pipe.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libseemore.so:system/vendor/lib/libseemore.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libst_disp.so:system/vendor/lib/libst_disp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libtrueportrait.so:system/vendor/lib/libtrueportrait.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libubifocus.so:system/vendor/lib/libubifocus.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libblurbuster.so:system/vendor/lib64/libblurbuster.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libcdsprpc.so:system/vendor/lib64/libcdsprpc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromaflash.so:system/vendor/lib64/libchromaflash.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libjni_blurbuster.so:system/vendor/lib64/libjni_blurbuster.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libjni_chromaflash.so:system/vendor/lib64/libjni_chromaflash.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libjni_clearsight.so:system/vendor/lib64/libjni_clearsight.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libjni_makeupV2.so:system/vendor/lib64/libjni_makeupV2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libjni_optizoom.so:system/vendor/lib64/libjni_optizoom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libjni_panorama.so:system/vendor/lib64/libjni_panorama.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libjni_sharpshooter.so:system/vendor/lib64/libjni_sharpshooter.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libjni_stillmore.so:system/vendor/lib64/libjni_stillmore.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libjni_trackingfocus.so:system/vendor/lib64/libjni_trackingfocus.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libjni_ubifocus.so:system/vendor/lib64/libjni_ubifocus.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liboptizoom.so:system/vendor/lib64/liboptizoom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libseemore.so:system/vendor/lib64/libseemore.so

PRODUCT_PACKAGES += \
    IFAAService \
    dashd

ifeq ($(QCPATH),)
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    $(LOCAL_PATH)/proprietary/bin/btnvtool:system/bin/btnvtool \
    $(LOCAL_PATH)/proprietary/bin/cnd:system/bin/cnd \
    $(LOCAL_PATH)/proprietary/bin/cnss-daemon:system/bin/cnss-daemon \
    $(LOCAL_PATH)/proprietary/bin/cnss_diag:system/bin/cnss_diag \
    $(LOCAL_PATH)/proprietary/bin/dpmd:system/bin/dpmd \
    $(LOCAL_PATH)/proprietary/bin/energy-awareness:system/bin/energy-awareness \
    $(LOCAL_PATH)/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    $(LOCAL_PATH)/proprietary/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
    $(LOCAL_PATH)/proprietary/bin/imscmservice:system/bin/imscmservice \
    $(LOCAL_PATH)/proprietary/bin/imsdatadaemon:system/bin/imsdatadaemon \
    $(LOCAL_PATH)/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon \
    $(LOCAL_PATH)/proprietary/bin/irsc_util:system/bin/irsc_util \
    $(LOCAL_PATH)/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    $(LOCAL_PATH)/proprietary/bin/lowi-server:system/bin/lowi-server \
    $(LOCAL_PATH)/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance \
    $(LOCAL_PATH)/proprietary/bin/netmgrd:system/bin/netmgrd \
    $(LOCAL_PATH)/proprietary/bin/pm-proxy:system/bin/pm-proxy \
    $(LOCAL_PATH)/proprietary/bin/pm-service:system/bin/pm-service \
    $(LOCAL_PATH)/proprietary/bin/qseecomd:system/bin/qseecomd \
    $(LOCAL_PATH)/proprietary/bin/qvop-daemon:system/bin/qvop-daemon \
    $(LOCAL_PATH)/proprietary/bin/radish:system/bin/radish \
    $(LOCAL_PATH)/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    $(LOCAL_PATH)/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    $(LOCAL_PATH)/proprietary/bin/tftp_server:system/bin/tftp_server \
    $(LOCAL_PATH)/proprietary/bin/time_daemon:system/bin/time_daemon \
    $(LOCAL_PATH)/proprietary/bin/wcnss_filter:system/bin/wcnss_filter \
    $(LOCAL_PATH)/proprietary/bin/xtwifi-client:system/bin/xtwifi-client \
    $(LOCAL_PATH)/proprietary/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent \
    $(LOCAL_PATH)/proprietary/etc/cacert_location.pem:system/etc/cacert_location.pem \
    $(LOCAL_PATH)/proprietary/etc/cne/SwimConfig.xml:system/etc/cne/SwimConfig.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/andsfCne.xml:system/etc/cne/andsfCne.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/ATT/ATT_profile1.xml:system/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/ATT/ATT_profile2.xml:system/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/ATT/ATT_profile3.xml:system/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/ATT/ATT_profile4.xml:system/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/ROW/ROW_profile1.xml:system/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/ROW/ROW_profile2.xml:system/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/ROW/ROW_profile3.xml:system/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/ROW/ROW_profile4.xml:system/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/ROW/ROW_profile5.xml:system/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/VZW/VZW_profile1.xml:system/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/VZW/VZW_profile2.xml:system/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/VZW/VZW_profile3.xml:system/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/VZW/VZW_profile4.xml:system/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/VZW/VZW_profile5.xml:system/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/wqeclient/VZW/VZW_profile6.xml:system/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    $(LOCAL_PATH)/proprietary/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
    $(LOCAL_PATH)/proprietary/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
    $(LOCAL_PATH)/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    $(LOCAL_PATH)/proprietary/etc/dpm/nsrm/NsrmConfiguration.xml:system/etc/dpm/nsrm/NsrmConfiguration.xml \
    $(LOCAL_PATH)/proprietary/etc/firmware/nvm_tlv.bin:system/etc/firmware/nvm_tlv.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/nvm_tlv_1.3.bin:system/etc/firmware/nvm_tlv_1.3.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/nvm_tlv_2.1.bin:system/etc/firmware/nvm_tlv_2.1.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/nvm_tlv_3.0.bin:system/etc/firmware/nvm_tlv_3.0.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/nvm_tlv_3.2.bin:system/etc/firmware/nvm_tlv_3.2.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/rampatch_tlv.img:system/etc/firmware/rampatch_tlv.img \
    $(LOCAL_PATH)/proprietary/etc/firmware/rampatch_tlv_1.3.tlv:system/etc/firmware/rampatch_tlv_1.3.tlv \
    $(LOCAL_PATH)/proprietary/etc/firmware/rampatch_tlv_2.1.tlv:system/etc/firmware/rampatch_tlv_2.1.tlv \
    $(LOCAL_PATH)/proprietary/etc/firmware/rampatch_tlv_3.0.tlv:system/etc/firmware/rampatch_tlv_3.0.tlv \
    $(LOCAL_PATH)/proprietary/etc/firmware/rampatch_tlv_3.2.tlv:system/etc/firmware/rampatch_tlv_3.2.tlv \
    $(LOCAL_PATH)/proprietary/etc/permissions/ConnectivityExt.xml:system/etc/permissions/ConnectivityExt.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/com.qti.snapdragon.sdk.display.xml:system/etc/permissions/com.qti.snapdragon.sdk.display.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/com.qualcomm.location.vzw_library.xml:system/etc/permissions/com.qualcomm.location.vzw_library.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/embms.xml:system/etc/permissions/embms.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/imscm.xml:system/etc/permissions/imscm.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/izat.xt.srv.xml:system/etc/permissions/izat.xt.srv.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/qti-vzw-ims-internal.xml:system/etc/permissions/qti-vzw-ims-internal.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    $(LOCAL_PATH)/proprietary/etc/thermal-engine.conf:system/etc/thermal-engine.conf \
    $(LOCAL_PATH)/proprietary/etc/xtra_root_cert.pem:system/etc/xtra_root_cert.pem \
    $(LOCAL_PATH)/proprietary/framework/ConnectivityExt.jar:system/framework/ConnectivityExt.jar \
    $(LOCAL_PATH)/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    $(LOCAL_PATH)/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    $(LOCAL_PATH)/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    $(LOCAL_PATH)/proprietary/framework/com.qti.location.sdk.jar:system/framework/com.qti.location.sdk.jar \
    $(LOCAL_PATH)/proprietary/framework/com.qti.snapdragon.sdk.display.jar:system/framework/com.qti.snapdragon.sdk.display.jar \
    $(LOCAL_PATH)/proprietary/framework/com.qualcomm.location.vzw_library.jar:system/framework/com.qualcomm.location.vzw_library.jar \
    $(LOCAL_PATH)/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    $(LOCAL_PATH)/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    $(LOCAL_PATH)/proprietary/framework/embmslibrary.jar:system/framework/embmslibrary.jar \
    $(LOCAL_PATH)/proprietary/framework/imscmlibrary.jar:system/framework/imscmlibrary.jar \
    $(LOCAL_PATH)/proprietary/framework/izat.xt.srv.jar:system/framework/izat.xt.srv.jar \
    $(LOCAL_PATH)/proprietary/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar \
    $(LOCAL_PATH)/proprietary/framework/rcsimssettings.jar:system/framework/rcsimssettings.jar \
    $(LOCAL_PATH)/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    $(LOCAL_PATH)/proprietary/lib/libOmxVpp.so:system/lib/libOmxVpp.so \
    $(LOCAL_PATH)/proprietary/lib/libvpplibrary.so:system/lib/libvpplibrary.so \
    $(LOCAL_PATH)/proprietary/lib64/libOmxVpp.so:system/lib64/libOmxVpp.so \
    $(LOCAL_PATH)/proprietary/lib64/libloc_ds_api.so:system/lib64/libloc_ds_api.so \
    $(LOCAL_PATH)/proprietary/lib64/libvpplibrary.so:system/lib64/libvpplibrary.so \
    $(LOCAL_PATH)/proprietary/vendor/bin/mm-pp-dpps:system/vendor/bin/mm-pp-dpps \
    $(LOCAL_PATH)/proprietary/vendor/bin/pd-mapper:system/vendor/bin/pd-mapper \
    $(LOCAL_PATH)/proprietary/vendor/bin/qseeproxydaemon:system/vendor/bin/qseeproxydaemon \
    $(LOCAL_PATH)/proprietary/vendor/bin/qti:system/vendor/bin/qti \
    $(LOCAL_PATH)/proprietary/vendor/bin/slim_daemon:system/vendor/bin/slim_daemon \
    $(LOCAL_PATH)/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    $(LOCAL_PATH)/proprietary/vendor/framework/qti-vzw-ims-internal.jar:system/vendor/framework/qti-vzw-ims-internal.jar \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/activity_recognition.msm8998.so:system/vendor/lib/hw/activity_recognition.msm8998.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/gatekeeper.msm8998.so:system/vendor/lib/hw/gatekeeper.msm8998.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/keystore.msm8998.so:system/vendor/lib/hw/keystore.msm8998.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/sound_trigger.primary.msm8998.so:system/vendor/lib/hw/sound_trigger.primary.msm8998.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/vulkan.msm8998.so:system/vendor/lib/hw/vulkan.msm8998.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxVideoDSMode.so:system/vendor/lib/libOmxVideoDSMode.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadm.so:system/vendor/lib/libadm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadsp_default_listener.so:system/vendor/lib/libadsp_default_listener.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadsp_hvx_callback_skel.so:system/vendor/lib/libadsp_hvx_callback_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadsp_hvx_stub.so:system/vendor/lib/libadsp_hvx_stub.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libc2d30-a5xx.so:system/vendor/lib/libc2d30-a5xx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libc2d30_bltlib.so:system/vendor/lib/libc2d30_bltlib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmctmgr.so:system/vendor/lib/libdpmctmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmfdmgr.so:system/vendor/lib/libdpmfdmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmnsrm.so:system/vendor/lib/libdpmnsrm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmtcm.so:system/vendor/lib/libdpmtcm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libhwdaphal.so:system/vendor/lib/libhwdaphal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libllvm-qgl.so:system/vendor/lib/libllvm-qgl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmiracast.so:system/vendor/lib/libmiracast.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqseed3.so:system/vendor/lib/libqseed3.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqvop-service.so:system/vendor/lib/libqvop-service.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsd_sdk_display.so:system/vendor/lib/libsd_sdk_display.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsdm-color.so:system/vendor/lib/libsdm-color.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsensor_test.so:system/vendor/lib/libsensor_test.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsensor_thresh.so:system/vendor/lib/libsensor_thresh.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsensor_user_cal.so:system/vendor/lib/libsensor_user_cal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsmwrapper.so:system/vendor/lib/libsmwrapper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libspl.so:system/vendor/lib/libspl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libvpphvx.so:system/vendor/lib/libvpphvx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libvqzip.so:system/vendor/lib/libvqzip.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwms.so:system/vendor/lib/libwms.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwqe.so:system/vendor/lib/libwqe.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/capi_v2_aptX_Classic.so:system/vendor/lib/rfsa/adsp/capi_v2_aptX_Classic.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/capi_v2_aptX_HD.so:system/vendor/lib/rfsa/adsp/capi_v2_aptX_HD.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libAudienceAZA.so:system/vendor/lib/rfsa/adsp/libAudienceAZA.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libFastRPC_AUE_Forward_skel.so:system/vendor/lib/rfsa/adsp/libFastRPC_AUE_Forward_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libFastRPC_UTF_Forward_800h_skel.so:system/vendor/lib/rfsa/adsp/libFastRPC_UTF_Forward_800h_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libFastRPC_UTF_Forward_Qtc2_skel.so:system/vendor/lib/rfsa/adsp/libFastRPC_UTF_Forward_Qtc2_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libFastRPC_UTF_Forward_skel.so:system/vendor/lib/rfsa/adsp/libFastRPC_UTF_Forward_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libadsp_fd_skel.so:system/vendor/lib/rfsa/adsp/libadsp_fd_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libadsp_hvx_add_constant.so:system/vendor/lib/rfsa/adsp/libadsp_hvx_add_constant.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libadsp_hvx_skel.so:system/vendor/lib/rfsa/adsp/libadsp_hvx_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libapps_mem_heap.so:system/vendor/lib/rfsa/adsp/libapps_mem_heap.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libdirac_capiv2.so:system/vendor/lib/rfsa/adsp/libdirac_capiv2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libedge_smooth_skel.so:system/vendor/lib/rfsa/adsp/libedge_smooth_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libobjectMattingApp_skel.so:system/vendor/lib/rfsa/adsp/libobjectMattingApp_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libqvr_adsp_driver_skel.so:system/vendor/lib/rfsa/adsp/libqvr_adsp_driver_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libscveBlobDescriptor_skel.so:system/vendor/lib/rfsa/adsp/libscveBlobDescriptor_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libscveCleverCapture_skel.so:system/vendor/lib/rfsa/adsp/libscveCleverCapture_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libscveFaceLandmark_skel.so:system/vendor/lib/rfsa/adsp/libscveFaceLandmark_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libscveFaceRecognition_skel.so:system/vendor/lib/rfsa/adsp/libscveFaceRecognition_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libscveObjectSegmentation_skel.so:system/vendor/lib/rfsa/adsp/libscveObjectSegmentation_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libscveT2T_skel.so:system/vendor/lib/rfsa/adsp/libscveT2T_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libscveTextReco_skel.so:system/vendor/lib/rfsa/adsp/libscveTextReco_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libscveVideoSummary_skel.so:system/vendor/lib/rfsa/adsp/libscveVideoSummary_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libvpp_frc.so:system/vendor/lib/rfsa/adsp/libvpp_frc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/rfsa/adsp/libvpp_svc_skel.so:system/vendor/lib/rfsa/adsp/libvpp_svc_skel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/sensor_calibrate.so:system/vendor/lib/sensor_calibrate.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/sensors.ssc.so:system/vendor/lib/sensors.ssc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libQTapGLES.so:system/vendor/lib64/egl/libQTapGLES.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/hw/activity_recognition.msm8998.so:system/vendor/lib64/hw/activity_recognition.msm8998.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/hw/flp.default.so:system/vendor/lib64/hw/flp.default.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/hw/gatekeeper.msm8998.so:system/vendor/lib64/hw/gatekeeper.msm8998.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/hw/keystore.msm8998.so:system/vendor/lib64/hw/keystore.msm8998.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/hw/vulkan.msm8998.so:system/vendor/lib64/hw/vulkan.msm8998.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-dplmedia.so:system/vendor/lib64/lib-dplmedia.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-ims-rcscmjni.so:system/vendor/lib64/lib-ims-rcscmjni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-imsSDP.so:system/vendor/lib64/lib-imsSDP.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-imscamera.so:system/vendor/lib64/lib-imscamera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-imsdpl.so:system/vendor/lib64/lib-imsdpl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-imsqimf.so:system/vendor/lib64/lib-imsqimf.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-imsrcs.so:system/vendor/lib64/lib-imsrcs.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-imsrcscm.so:system/vendor/lib64/lib-imsrcscm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-imsrcscmclient.so:system/vendor/lib64/lib-imsrcscmclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-imsrcscmservice.so:system/vendor/lib64/lib-imsrcscmservice.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-imss.so:system/vendor/lib64/lib-imss.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-imsvt.so:system/vendor/lib64/lib-imsvt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-imsxml.so:system/vendor/lib64/lib-imsxml.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-rcsimssjni.so:system/vendor/lib64/lib-rcsimssjni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-rcsjni.so:system/vendor/lib64/lib-rcsjni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-rtpcommon.so:system/vendor/lib64/lib-rtpcommon.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-rtpcore.so:system/vendor/lib64/lib-rtpcore.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-rtpdaemoninterface.so:system/vendor/lib64/lib-rtpdaemoninterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-rtpsl.so:system/vendor/lib64/lib-rtpsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-sec-disp.so:system/vendor/lib64/lib-sec-disp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libDRPlugin.so:system/vendor/lib64/libDRPlugin.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libGPreqcancel.so:system/vendor/lib64/libGPreqcancel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libGPreqcancel_svc.so:system/vendor/lib64/libGPreqcancel_svc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libI420colorconvert.so:system/vendor/lib64/libI420colorconvert.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libOmxAacDec.so:system/vendor/lib64/libOmxAacDec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libOmxEvrcDec.so:system/vendor/lib64/libOmxEvrcDec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libOmxQcelp13Dec.so:system/vendor/lib64/libOmxQcelp13Dec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libQtiTether.so:system/vendor/lib64/libQtiTether.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libSecureUILib.so:system/vendor/lib64/libSecureUILib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libStDrvInt.so:system/vendor/lib64/libStDrvInt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libTimeService.so:system/vendor/lib64/libTimeService.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libadsp_default_listener.so:system/vendor/lib64/libadsp_default_listener.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libalarmservice_jni.so:system/vendor/lib64/libalarmservice_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libbccQTI.so:system/vendor/lib64/libbccQTI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libc2d30-a5xx.so:system/vendor/lib64/libc2d30-a5xx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libc2d30_bltlib.so:system/vendor/lib64/libc2d30_bltlib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libcne.so:system/vendor/lib64/libcne.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libcneqmiutils.so:system/vendor/lib64/libcneqmiutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libconnctrl.so:system/vendor/lib64/libconnctrl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdataitems.so:system/vendor/lib64/libdataitems.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdisp-aba.so:system/vendor/lib64/libdisp-aba.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdpmctmgr.so:system/vendor/lib64/libdpmctmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdpmfdmgr.so:system/vendor/lib64/libdpmfdmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdpmframework.so:system/vendor/lib64/libdpmframework.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdpmnsrm.so:system/vendor/lib64/libdpmnsrm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdpmtcm.so:system/vendor/lib64/libdpmtcm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdrplugin_client.so:system/vendor/lib64/libdrplugin_client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libevent_observer.so:system/vendor/lib64/libevent_observer.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libfastcvadsp_stub.so:system/vendor/lib64/libfastcvadsp_stub.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libfastcvopt.so:system/vendor/lib64/libfastcvopt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libflp.so:system/vendor/lib64/libflp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libgdtap.so:system/vendor/lib64/libgdtap.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libhwdaphal.so:system/vendor/lib64/libhwdaphal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libimscamera_jni.so:system/vendor/lib64/libimscamera_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libimsmedia_jni.so:system/vendor/lib64/libimsmedia_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libizat_client_api.so:system/vendor/lib64/libizat_client_api.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libllvm-qgl.so:system/vendor/lib64/libllvm-qgl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libloc_ext.so:system/vendor/lib64/libloc_ext.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblocationservice.so:system/vendor/lib64/liblocationservice.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblocationservice_glue.so:system/vendor/lib64/liblocationservice_glue.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblowi_client.so:system/vendor/lib64/liblowi_client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblowi_wifihal.so:system/vendor/lib64/liblowi_wifihal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblowi_wifihal_nl.so:system/vendor/lib64/liblowi_wifihal_nl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblqe.so:system/vendor/lib64/liblqe.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmiracast.so:system/vendor/lib64/libmiracast.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmm-color-convertor.so:system/vendor/lib64/libmm-color-convertor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmm-disp-apis.so:system/vendor/lib64/libmm-disp-apis.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmmosal.so:system/vendor/lib64/libmmosal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libpdmapper.so:system/vendor/lib64/libpdmapper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libpdnotifier.so:system/vendor/lib64/libpdnotifier.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libprotobuf-cpp-lgcy.so:system/vendor/lib64/libprotobuf-cpp-lgcy.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqcmaputils.so:system/vendor/lib64/libqcmaputils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqisl.so:system/vendor/lib64/libqisl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqseed3.so:system/vendor/lib64/libqseed3.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libquipc_os_api.so:system/vendor/lib64/libquipc_os_api.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqvop-service.so:system/vendor/lib64/libqvop-service.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/librcc.so:system/vendor/lib64/librcc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libril-qc-ltedirectdisc.so:system/vendor/lib64/libril-qc-ltedirectdisc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libril-qc-radioconfig.so:system/vendor/lib64/libril-qc-radioconfig.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/librilqmiservices.so:system/vendor/lib64/librilqmiservices.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsd_sdk_display.so:system/vendor/lib64/libsd_sdk_display.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsdm-color.so:system/vendor/lib64/libsdm-color.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsdm-diag.so:system/vendor/lib64/libsdm-diag.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsdmextension.so:system/vendor/lib64/libsdmextension.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsecureui.so:system/vendor/lib64/libsecureui.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsecureui_svcsock.so:system/vendor/lib64/libsecureui_svcsock.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsensor1.so:system/vendor/lib64/libsensor1.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsensor_reg.so:system/vendor/lib64/libsensor_reg.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsensor_test.so:system/vendor/lib64/libsensor_test.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsensor_thresh.so:system/vendor/lib64/libsensor_thresh.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsensor_user_cal.so:system/vendor/lib64/libsensor_user_cal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsettings.so:system/vendor/lib64/libsettings.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libspl.so:system/vendor/lib64/libspl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libuiblur.so:system/vendor/lib64/libuiblur.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libulp2.so:system/vendor/lib64/libulp2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libvendorconn.so:system/vendor/lib64/libvendorconn.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libvoice-svc.so:system/vendor/lib64/libvoice-svc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libvpphvx.so:system/vendor/lib64/libvpphvx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwms.so:system/vendor/lib64/libwms.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwqe.so:system/vendor/lib64/libwqe.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libxt_native.so:system/vendor/lib64/libxt_native.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libxtadapter.so:system/vendor/lib64/libxtadapter.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libxtwifi_ulp_adaptor.so:system/vendor/lib64/libxtwifi_ulp_adaptor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/sensor_calibrate.so:system/vendor/lib64/sensor_calibrate.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/sensors.ssc.so:system/vendor/lib64/sensors.ssc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/soundfx/libqcbassboost.so:system/vendor/lib64/soundfx/libqcbassboost.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/soundfx/libqcreverb.so:system/vendor/lib64/soundfx/libqcreverb.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/soundfx/libqcvirt.so:system/vendor/lib64/soundfx/libqcvirt.so \
    $(LOCAL_PATH)/proprietary/vendor/qcril.db:system/vendor/qcril.db

PRODUCT_PACKAGES += \
    libloc_api_v02 \
    libbtnv \
    libgpustats \
    libsdm-disp-apis \
    libthermalclient \
    libtime_genoff \
    QtiTelephonyService \
    TimeService \
    datastatusnotification \
    embms \
    shutdownlistener \
    QtiTetherService \
    com.qualcomm.location \
    qcrilmsgtunnel \
    colorservice \
    qcnvitems \
    qcrilhook
endif

-include vendor/extra/devices.mk
ifneq ($(call is-qc-perf-target),true)
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/bin/iop:system/bin/iop \
    $(LOCAL_PATH)/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    $(LOCAL_PATH)/proprietary/vendor/etc/perf-profile0.conf:system/vendor/etc/perf-profile0.conf \
    $(LOCAL_PATH)/proprietary/vendor/etc/perf-profile1.conf:system/vendor/etc/perf-profile1.conf \
    $(LOCAL_PATH)/proprietary/vendor/etc/perf-profile2.conf:system/vendor/etc/perf-profile2.conf \
    $(LOCAL_PATH)/proprietary/vendor/etc/perf-profile3.conf:system/vendor/etc/perf-profile3.conf \
    $(LOCAL_PATH)/proprietary/vendor/etc/perf-profile4.conf:system/vendor/etc/perf-profile4.conf \
    $(LOCAL_PATH)/proprietary/vendor/etc/perf-profile5.conf:system/vendor/etc/perf-profile5.conf \
    $(LOCAL_PATH)/proprietary/vendor/etc/perf-profile6.conf:system/vendor/etc/perf-profile6.conf \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqti-iop-client.so:system/vendor/lib/libqti-iop-client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqti-iop.so:system/vendor/lib/libqti-iop.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqti-util.so:system/vendor/lib/libqti-util.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqti-utils.so:system/vendor/lib/libqti-utils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqti-iop-client.so:system/vendor/lib64/libqti-iop-client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqti-iop.so:system/vendor/lib64/libqti-iop.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqti-util.so:system/vendor/lib64/libqti-util.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqti-utils.so:system/vendor/lib64/libqti-utils.so
endif

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/vendor/firmware/widevine.b00:system/vendor/firmware/widevine.b00 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/widevine.b01:system/vendor/firmware/widevine.b01 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/widevine.b02:system/vendor/firmware/widevine.b02 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/widevine.b03:system/vendor/firmware/widevine.b03 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/widevine.b04:system/vendor/firmware/widevine.b04 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/widevine.b05:system/vendor/firmware/widevine.b05 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/widevine.b06:system/vendor/firmware/widevine.b06 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/widevine.mdt:system/vendor/firmware/widevine.mdt \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwvhidl.so:system/vendor/lib/libwvhidl.so \
    $(LOCAL_PATH)/proprietary/vendor/bin/hw/android.hardware.drm@1.0-service.widevine:system/vendor/bin/hw/android.hardware.drm@1.0-service.widevine \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/android.hardware.drm@1.0-service.widevine.rc:system/vendor/etc/init/android.hardware.drm@1.0-service.widevine.rc \
    $(LOCAL_PATH)/proprietary/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcppf.so:system/vendor/lib/libcppf.so

